### PR TITLE
adds a dropout to layers that combines training and test operation

### PR DESCRIPTION
**Pull request by jrock08**

### CODE REVIEW

**Comment by kevjshih** [comment]
I suppose my only comment is that maybe we should keep the seed option available (with default None), in case someone needs it for reproducability. Otherwise LGTM.

**Comment by kevjshih** [comment]
Ok, well that looks good. Merge whenever ready.

**Comment by jrock08** [comment]
I figured there was no reason to leave out shape if I was going to expose seed as well.

**Comment by kevjshih** [comment]
Yeah, that makes sense.

**Pull request merged**
